### ISSUE TITLE
Best Target Finalized block is empty

### ISSUE THREAD

**Issue by tomusdrw** [hbulgarini/bridge-ui-substrate-draft#4]
There is no value displayed on both chains:
![image](https://user-images.githubusercontent.com/581548/108984329-12572000-7690-11eb-8bc5-406c82c12f08.png)

**Comment by hbulgarini** [comment]
@tomusdrw , could you please confirm if this issue is because you don't have your `.env` setup?

**Comment by tomusdrw** [comment]
Works in #1 now.

**Comment by hbulgarini** [comment]
Closes #1
